name       : ibus-cangjie
version    : 2.4
release    : 2
source     :
    - https://github.com/Cangjians/ibus-cangjie/releases/download/v2.4/ibus-cangjie-2.4.tar.xz : 299a60f1df063bfadc68c5420cbddb5d1a0de31935d95e414f75e0f93e27ba49
license    : GPL-3.0
component  : desktop.library
summary    : This is an IBus engine for users of the Cangjie and Quick input methods.
description: |
    This is an IBus engine for users of the Cangjie and Quick input methods.
builddeps  :
    - pkgconfig(ibus-1.0)
    - pycangjie
    - python3-gobject-devel
rundeps    :
    - pycangjie
    - python3-gobject
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
